# Generated by Django 5.2.4 on 2025-07-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('empaque', 'Empaque'), ('prensa', 'Prensa')], max_length=20)),
                ('capacidad_teorica', models.FloatField(help_text='KG/H o Bultos/H')),
                ('capacidad_real', models.FloatField(help_text='Capacidad real promedio')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Área de Producción',
                'verbose_name_plural': 'Áreas de Producción',
            },
        ),
    ]
