# Generated by Django 5.2.4 on 2025-07-05 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroOEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno', models.CharField(choices=[('A', 'Turno A (06:00-14:00)'), ('B', 'Turno B (14:00-22:00)'), ('C', 'Turno C (22:00-06:00)')], max_length=1)),
                ('plan_produccion', models.FloatField()),
                ('produccion_real', models.FloatField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('observaciones', models.TextField(blank=True)),
                ('formato_producto', models.CharField(blank=True, max_length=100)),
                ('produccion_kg', models.FloatField(blank=True, null=True)),
                ('lectura_inicial', models.FloatField(blank=True, null=True)),
                ('lectura_final', models.FloatField(blank=True, null=True)),
                ('paradas', models.IntegerField(default=0)),
                ('motivo_parada', models.CharField(blank=True, max_length=200)),
                ('disponibilidad', models.FloatField(default=0)),
                ('rendimiento', models.FloatField(default=0)),
                ('calidad', models.FloatField(default=100)),
                ('oee', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.area')),
            ],
            options={
                'verbose_name': 'Registro OEE',
                'verbose_name_plural': 'Registros OEE',
            },
        ),
    ]
